### ISSUE TITLE
SSL error due to packaging issue makes Tokodon v24.02+ stop working

### ISSUE THREAD

**Issue by Thanh9356** [flathub/org.kde.tokodon#59]
Reproduce:

1. Install from flatpak command: `flatpak install --user flathub org.kde.tokodon`
2. Run Tokodon from application launcher
3. Choose Login, type the instance URL: `mastodon.social`. Tokodon gives me to Authorization page
4. A blank page

Expected behavior: Tokodon full loads the authorization, giving me to the Mastodon login page within the app.

Logs from console: 
```
[2:39:0430/234759.754052:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[2:39:0430/234759.786208:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for mastodon.social failed:
----- Certificate i=3 (CN=DST Root CA X3,O=Digital Signature Trust Co.) -----
ERROR: No matching issuer found


[2:57:0430/234759.786740:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -202
```

I'm sure that it's not Tokodon's bug but Flathub packaging bug, I have tried native package but nothing was wrong.

**Comment by travier** [comment]
What's your distribution and version?

**Comment by Thanh9356** [comment]
> What's your distribution and version?

Distro: openSUSE MicroOS
Tokodon version: 24.02.2

**Comment by Thanh9356** [comment]
> can reproduce on openSUSE Tumbleweed

I don't know... I tested a openSUSE Tumbleweed container but nothing was wrong... I don't know where this issue comes from

**Comment by Thanh9356** [comment]
it seems the developers of Tokodon tried another approach to handle the login, it's now resolved, closing this issue.
